[ 2023-04-23 04:43:40,812 ] root - INFO - Entered the start_data_ingestion method of TrainPipeline class
[ 2023-04-23 04:43:40,812 ] root - INFO - Starting data ingestion
[ 2023-04-23 04:43:40,831 ] root - INFO - Consider Local csv file
[ 2023-04-23 04:43:41,740 ] root - INFO - Shape of dataframe: (36188, 171)
[ 2023-04-23 04:43:41,805 ] root - INFO - Shape of dataframe: (36188, 164)
[ 2023-04-23 04:43:41,805 ] root - INFO - Saving exported data into feature store file path: artifact/04_23_2023_04_43_40/data_ingestion/feature_store/sensor.csv
[ 2023-04-23 04:43:42,538 ] root - INFO - Shape of dataframe: (36188, 164)
[ 2023-04-23 04:43:42,538 ] root - INFO - Starting the train and test splittings
[ 2023-04-23 04:43:44,053 ] root - INFO - Data ingestion completed and artifact: DataIngestionArtifact(trained_file_path='artifact/04_23_2023_04_43_40/data_ingestion/ingested/train.csv', test_file_path='artifact/04_23_2023_04_43_40/data_ingestion/ingested/test.csv')
[ 2023-04-23 04:43:45,165 ] root - INFO - Missing numerical column: []
[ 2023-04-23 04:43:45,165 ] root - INFO - Valid Numerical Column : True
[ 2023-04-23 04:43:45,165 ] root - INFO - Missing numerical column: []
[ 2023-04-23 04:43:45,165 ] root - INFO - Required number of columns: 164
[ 2023-04-23 04:43:45,165 ] root - INFO - Data frame has columns: 164
[ 2023-04-23 04:43:45,165 ] root - INFO - Required number of columns: 164
[ 2023-04-23 04:43:45,165 ] root - INFO - Data frame has columns: 164
[ 2023-04-23 04:43:49,986 ] root - INFO - Data validation artifact: DataValidationArtifact(validation_status=False, valid_train_file_path='artifact/04_23_2023_04_43_40/data_ingestion/ingested/train.csv', valid_test_file_path='artifact/04_23_2023_04_43_40/data_ingestion/ingested/test.csv', invalid_train_file_path=None, invalid_test_file_path=None, drift_report_file_path='artifact/04_23_2023_04_43_40/data_validation/drift_report/report.yaml')
[ 2023-04-23 04:43:50,023 ] root - INFO - Error occurred python script name [main.py] line number [8] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/pipeline/training_pipeline.py] line number [81] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/pipeline/training_pipeline.py] line number [58] error message ['TrainPipeline' object has no attribute 'data_transformation_config']]]
