[ 2023-04-23 15:21:02,086 ] root - INFO - Entered the start_data_ingestion method of TrainPipeline class
[ 2023-04-23 15:21:02,086 ] root - INFO - Starting data ingestion
[ 2023-04-23 15:21:02,112 ] root - INFO - Consider Local csv file
[ 2023-04-23 15:21:03,170 ] root - INFO - Shape of dataframe: (36188, 171)
[ 2023-04-23 15:21:03,246 ] root - INFO - Shape of dataframe: (36188, 164)
[ 2023-04-23 15:21:03,247 ] root - INFO - Saving exported data into feature store file path: artifact/04_23_2023_15_21_01/data_ingestion/feature_store/sensor.csv
[ 2023-04-23 15:21:03,964 ] root - INFO - Shape of dataframe: (36188, 164)
[ 2023-04-23 15:21:03,965 ] root - INFO - Starting the train and test splittings
[ 2023-04-23 15:21:05,544 ] root - INFO - Data ingestion completed and artifact: DataIngestionArtifact(trained_file_path='artifact/04_23_2023_15_21_01/data_ingestion/ingested/train.csv', test_file_path='artifact/04_23_2023_15_21_01/data_ingestion/ingested/test.csv')
[ 2023-04-23 15:21:06,528 ] root - INFO - Missing numerical column: []
[ 2023-04-23 15:21:06,528 ] root - INFO - Valid Numerical Column : True
[ 2023-04-23 15:21:06,528 ] root - INFO - Missing numerical column: []
[ 2023-04-23 15:21:06,528 ] root - INFO - Required number of columns: 164
[ 2023-04-23 15:21:06,528 ] root - INFO - Data frame has columns: 164
[ 2023-04-23 15:21:06,528 ] root - INFO - Required number of columns: 164
[ 2023-04-23 15:21:06,528 ] root - INFO - Data frame has columns: 164
[ 2023-04-23 15:21:11,309 ] root - INFO - Data validation artifact: DataValidationArtifact(validation_status=False, valid_train_file_path='artifact/04_23_2023_15_21_01/data_ingestion/ingested/train.csv', valid_test_file_path='artifact/04_23_2023_15_21_01/data_ingestion/ingested/test.csv', invalid_train_file_path=None, invalid_test_file_path=None, drift_report_file_path='artifact/04_23_2023_15_21_01/data_validation/drift_report/report.yaml')
[ 2023-04-23 15:21:11,348 ] root - INFO - Starting data transformation
[ 2023-04-23 15:21:11,348 ] root - INFO - Error occurred python script name [main.py] line number [8] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/pipeline/training_pipeline.py] line number [82] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/pipeline/training_pipeline.py] line number [60] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/components/data_transformation.py] line number [91] error message [type object 'DataTransformation' has no attribute 'get_data_transformer_object']]]]
