[ 2023-04-23 13:46:19,569 ] root - INFO - Entered the start_data_ingestion method of TrainPipeline class
[ 2023-04-23 13:46:19,569 ] root - INFO - Starting data ingestion
[ 2023-04-23 13:46:19,589 ] root - INFO - Consider Local csv file
[ 2023-04-23 13:46:20,684 ] root - INFO - Shape of dataframe: (36188, 171)
[ 2023-04-23 13:46:20,770 ] root - INFO - Shape of dataframe: (36188, 164)
[ 2023-04-23 13:46:20,770 ] root - INFO - Saving exported data into feature store file path: artifact/04_23_2023_13_46_18/data_ingestion/feature_store/sensor.csv
[ 2023-04-23 13:46:21,583 ] root - INFO - Shape of dataframe: (36188, 164)
[ 2023-04-23 13:46:21,583 ] root - INFO - Starting the train and test splittings
[ 2023-04-23 13:46:22,975 ] root - INFO - Data ingestion completed and artifact: DataIngestionArtifact(trained_file_path='artifact/04_23_2023_13_46_18/data_ingestion/ingested/train.csv', test_file_path='artifact/04_23_2023_13_46_18/data_ingestion/ingested/test.csv')
[ 2023-04-23 13:46:23,876 ] root - INFO - Missing numerical column: []
[ 2023-04-23 13:46:23,876 ] root - INFO - Valid Numerical Column : True
[ 2023-04-23 13:46:23,876 ] root - INFO - Missing numerical column: []
[ 2023-04-23 13:46:23,876 ] root - INFO - Required number of columns: 164
[ 2023-04-23 13:46:23,876 ] root - INFO - Data frame has columns: 164
[ 2023-04-23 13:46:23,876 ] root - INFO - Required number of columns: 164
[ 2023-04-23 13:46:23,876 ] root - INFO - Data frame has columns: 164
[ 2023-04-23 13:46:28,643 ] root - INFO - Data validation artifact: DataValidationArtifact(validation_status=True, valid_train_file_path='artifact/04_23_2023_13_46_18/data_ingestion/ingested/train.csv', valid_test_file_path='artifact/04_23_2023_13_46_18/data_ingestion/ingested/test.csv', invalid_train_file_path=None, invalid_test_file_path=None, drift_report_file_path='artifact/04_23_2023_13_46_18/data_validation/drift_report/report.yaml')
[ 2023-04-23 13:46:28,682 ] root - INFO - Starting data transformation
[ 2023-04-23 13:46:28,682 ] root - INFO - Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/main.py] line number [8] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/pipeline/training_pipeline.py] line number [82] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/pipeline/training_pipeline.py] line number [60] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/components/data_transformation.py] 
line number [91] error message ['DataTransformation' object has no attribute 'get_data_transformer_object']]]]
