[ 2023-04-25 01:22:01,484 ] root - INFO - Entered the start_data_ingestion method of TrainPipeline class
[ 2023-04-25 01:22:01,485 ] root - INFO - Starting data ingestion
[ 2023-04-25 01:22:01,621 ] root - INFO - Consider Local csv file
[ 2023-04-25 01:22:02,773 ] root - INFO - Shape of dataframe: (36188, 171)
[ 2023-04-25 01:22:02,840 ] root - INFO - Shape of dataframe: (36188, 164)
[ 2023-04-25 01:22:02,841 ] root - INFO - Saving exported data into feature store file path: artifact/04_25_2023_01_21_55/data_ingestion/feature_store/sensor.csv
[ 2023-04-25 01:22:03,604 ] root - INFO - Shape of dataframe: (36188, 164)
[ 2023-04-25 01:22:03,604 ] root - INFO - Starting the train and test splittings
[ 2023-04-25 01:22:05,063 ] root - INFO - Data ingestion completed and artifact: DataIngestionArtifact(trained_file_path='artifact/04_25_2023_01_21_55/data_ingestion/ingested/train.csv', test_file_path='artifact/04_25_2023_01_21_55/data_ingestion/ingested/test.csv')
[ 2023-04-25 01:22:08,508 ] root - INFO - Missing numerical column: []
[ 2023-04-25 01:22:08,508 ] root - INFO - Valid Numerical Column : True
[ 2023-04-25 01:22:08,508 ] root - INFO - Missing numerical column: []
[ 2023-04-25 01:22:08,509 ] root - INFO - Required number of columns: 164
[ 2023-04-25 01:22:08,509 ] root - INFO - Data frame has columns: 164
[ 2023-04-25 01:22:08,509 ] root - INFO - Required number of columns: 164
[ 2023-04-25 01:22:08,509 ] root - INFO - Data frame has columns: 164
[ 2023-04-25 01:22:13,804 ] root - INFO - Data validation artifact: DataValidationArtifact(validation_status=False, valid_train_file_path='artifact/04_25_2023_01_21_55/data_ingestion/ingested/train.csv', valid_test_file_path='artifact/04_25_2023_01_21_55/data_ingestion/ingested/test.csv', invalid_train_file_path=None, invalid_test_file_path=None, drift_report_file_path='artifact/04_25_2023_01_21_55/data_validation/drift_report/report.yaml')
[ 2023-04-25 01:22:39,220 ] root - INFO - Entered the save_object method of MainUtils class
[ 2023-04-25 01:22:39,230 ] root - INFO - Exited the save_object method of MainUtils class
[ 2023-04-25 01:22:39,230 ] root - INFO - Data transformation artifact: DataTransformationArtifact(transformed_object_file_path='artifact/04_25_2023_01_21_55/data_transformation/transformed_object/preprocessing.pkl', transformed_train_file_path='artifact/04_25_2023_01_21_55/data_transformation/transformed/train.npy', transformed_test_file_path='artifact/04_25_2023_01_21_55/data_transformation/transformed/test.npy')
[ 2023-04-25 01:23:00,157 ] root - INFO - Entered the load_object method of MainUtils class
[ 2023-04-25 01:23:00,158 ] root - INFO - Exited the load_object method of MainUtils class
[ 2023-04-25 01:23:00,158 ] root - INFO - Entered the save_object method of MainUtils class
[ 2023-04-25 01:23:00,169 ] root - INFO - Exited the save_object method of MainUtils class
[ 2023-04-25 01:23:00,170 ] root - INFO - Model trainer artifact: ModelTrainerArtifact(trained_model_file_path='artifact/04_25_2023_01_21_55/model_trainer/trained_model/model.pkl', train_metric_artifact=ClassificationMetricArtifact(f1_score=1.0, precision_score=1.0, recall_score=1.0), test_metric_artifact=ClassificationMetricArtifact(f1_score=0.970291233718718, precision_score=0.992069429896753, recall_score=0.9494486610339395))
[ 2023-04-25 01:23:09,425 ] root - INFO - Model evaluation artifact: ModelEvaluationArtifact(is_model_accepted=True, improved_accuracy=None, best_model_path=None, trained_model_path='artifact/04_25_2023_01_21_55/model_trainer/trained_model/model.pkl', train_model_metric_artifact=ClassificationMetricArtifact(f1_score=0.970291233718718, precision_score=0.992069429896753, recall_score=0.9494486610339395), best_model_metric_artifact=None)
[ 2023-04-25 01:23:55,592 ] root - INFO - I'm Entring into initialize_model_pusher and trained_model_path
[ 2023-04-25 01:24:07,676 ] root - INFO - Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/main.py] line number [8] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/pipeline/training_pipeline.py] line number [131] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/pipeline/training_pipeline.py] line number [110] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/components/mode_pusher.py] line number [24] error message ['ModelTrainerArtifact' object has no attribute 'trained_model_path']]]]
