[ 2023-04-23 04:12:57,016 ] root - INFO - Entered the start_data_ingestion method of TrainPipeline class
[ 2023-04-23 04:12:57,016 ] root - INFO - Starting data ingestion
[ 2023-04-23 04:12:57,036 ] root - INFO - Consider Local csv file
[ 2023-04-23 04:12:57,962 ] root - INFO - Shape of dataframe: (36188, 171)
[ 2023-04-23 04:12:58,023 ] root - INFO - Shape of dataframe: (36188, 164)
[ 2023-04-23 04:12:58,023 ] root - INFO - Saving exported data into feature store file path: artifact/04_23_2023_04_12_56/data_ingestion/feature_store/sensor.csv
[ 2023-04-23 04:12:58,675 ] root - INFO - Shape of dataframe: (36188, 164)
[ 2023-04-23 04:12:58,675 ] root - INFO - Starting the train and test splittings
[ 2023-04-23 04:13:00,164 ] root - INFO - Data ingestion completed and artifact: DataIngestionArtifact(trained_file_path='artifact/04_23_2023_04_12_56/data_ingestion/ingested/train.csv', test_file_path='artifact/04_23_2023_04_12_56/data_ingestion/ingested/test.csv')
[ 2023-04-23 04:13:01,115 ] root - INFO - Missing numerical column: []
[ 2023-04-23 04:13:01,116 ] root - INFO - Valid Numerical Column : True
[ 2023-04-23 04:13:01,116 ] root - INFO - Missing numerical column: []
[ 2023-04-23 04:13:01,116 ] root - INFO - Required number of columns: 164
[ 2023-04-23 04:13:01,116 ] root - INFO - Data frame has columns: 164
[ 2023-04-23 04:13:01,116 ] root - INFO - Required number of columns: 164
[ 2023-04-23 04:13:01,116 ] root - INFO - Data frame has columns: 164
[ 2023-04-23 04:13:06,424 ] root - INFO - Data validation artifact: DataValidationArtifact(validation_status=False, valid_train_file_path='artifact/04_23_2023_04_12_56/data_ingestion/ingested/train.csv', valid_test_file_path='artifact/04_23_2023_04_12_56/data_ingestion/ingested/test.csv', invalid_train_file_path=None, invalid_test_file_path=None, drift_report_file_path='artifact/04_23_2023_04_12_56/data_validation/drift_report/report.yaml')
[ 2023-04-23 04:13:06,471 ] root - INFO - Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/main.py] line number [8] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/pipeline/training_pipeline.py] line number [81] error message [start_data_transformation() got an unexpected keyword argument 'data_validation_artifact']]
