[ 2023-04-25 01:16:34,690 ] root - INFO - Entered the start_data_ingestion method of TrainPipeline class
[ 2023-04-25 01:16:34,690 ] root - INFO - Starting data ingestion
[ 2023-04-25 01:16:34,709 ] root - INFO - Consider Local csv file
[ 2023-04-25 01:16:35,823 ] root - INFO - Shape of dataframe: (36188, 171)
[ 2023-04-25 01:16:35,902 ] root - INFO - Shape of dataframe: (36188, 164)
[ 2023-04-25 01:16:35,902 ] root - INFO - Saving exported data into feature store file path: artifact/04_25_2023_01_16_33/data_ingestion/feature_store/sensor.csv
[ 2023-04-25 01:16:36,710 ] root - INFO - Shape of dataframe: (36188, 164)
[ 2023-04-25 01:16:36,710 ] root - INFO - Starting the train and test splittings
[ 2023-04-25 01:16:38,082 ] root - INFO - Data ingestion completed and artifact: DataIngestionArtifact(trained_file_path='artifact/04_25_2023_01_16_33/data_ingestion/ingested/train.csv', test_file_path='artifact/04_25_2023_01_16_33/data_ingestion/ingested/test.csv')
[ 2023-04-25 01:16:39,078 ] root - INFO - Missing numerical column: []
[ 2023-04-25 01:16:39,078 ] root - INFO - Valid Numerical Column : True
[ 2023-04-25 01:16:39,078 ] root - INFO - Missing numerical column: []
[ 2023-04-25 01:16:39,078 ] root - INFO - Required number of columns: 164
[ 2023-04-25 01:16:39,078 ] root - INFO - Data frame has columns: 164
[ 2023-04-25 01:16:39,078 ] root - INFO - Required number of columns: 164
[ 2023-04-25 01:16:39,078 ] root - INFO - Data frame has columns: 164
[ 2023-04-25 01:16:44,087 ] root - INFO - Data validation artifact: DataValidationArtifact(validation_status=True, valid_train_file_path='artifact/04_25_2023_01_16_33/data_ingestion/ingested/train.csv', valid_test_file_path='artifact/04_25_2023_01_16_33/data_ingestion/ingested/test.csv', invalid_train_file_path=None, invalid_test_file_path=None, drift_report_file_path='artifact/04_25_2023_01_16_33/data_validation/drift_report/report.yaml')
[ 2023-04-25 01:17:10,024 ] root - INFO - Entered the save_object method of MainUtils class
[ 2023-04-25 01:17:10,027 ] root - INFO - Exited the save_object method of MainUtils class
[ 2023-04-25 01:17:10,027 ] root - INFO - Data transformation artifact: DataTransformationArtifact(transformed_object_file_path='artifact/04_25_2023_01_16_33/data_transformation/transformed_object/preprocessing.pkl', transformed_train_file_path='artifact/04_25_2023_01_16_33/data_transformation/transformed/train.npy', transformed_test_file_path='artifact/04_25_2023_01_16_33/data_transformation/transformed/test.npy')
[ 2023-04-25 01:17:27,382 ] root - INFO - Entered the load_object method of MainUtils class
[ 2023-04-25 01:17:27,383 ] root - INFO - Exited the load_object method of MainUtils class
[ 2023-04-25 01:17:27,383 ] root - INFO - Entered the save_object method of MainUtils class
[ 2023-04-25 01:17:27,389 ] root - INFO - Exited the save_object method of MainUtils class
[ 2023-04-25 01:17:27,389 ] root - INFO - Model trainer artifact: ModelTrainerArtifact(trained_model_file_path='artifact/04_25_2023_01_16_33/model_trainer/trained_model/model.pkl', train_metric_artifact=ClassificationMetricArtifact(f1_score=1.0, precision_score=1.0, recall_score=1.0), test_metric_artifact=ClassificationMetricArtifact(f1_score=0.9727985922721607, precision_score=0.9951995199519952, recall_score=0.9513839093646924))
[ 2023-04-25 01:17:28,871 ] root - INFO - Model evaluation artifact: ModelEvaluationArtifact(is_model_accepted=True, improved_accuracy=None, best_model_path=None, trained_model_path='artifact/04_25_2023_01_16_33/model_trainer/trained_model/model.pkl', train_model_metric_artifact=ClassificationMetricArtifact(f1_score=0.9727985922721607, precision_score=0.9951995199519952, recall_score=0.9513839093646924), best_model_metric_artifact=None)
[ 2023-04-25 01:17:28,934 ] root - INFO - I'm Entring into initialize_model_pusher and trained_model_path
[ 2023-04-25 01:17:28,934 ] root - INFO - Error occurred python script name [main.py] line number [8] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/pipeline/training_pipeline.py] line number [131] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/pipeline/training_pipeline.py] line number [110] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/components/mode_pusher.py] line number [24] error message ['ModelTrainerArtifact' object has no attribute 'trained_model_path']]]]
